import { PrismaPg } from "@prisma/adapter-pg";
import { PrismaClient, type Prisma } from "../src/generated/prisma/client";

const connectionString = process.env.DATABASE_URL;

if (!connectionString) {
  throw new Error("DATABASE_URL 환경 변수가 필요합니다.");
}

const prisma = new PrismaClient({
  adapter: new PrismaPg({ connectionString }),
});

type ColumnType = "text" | "number" | "date" | "boolean";
type SeedSheet = {
  id: string;
  name: string;
  columns: string[];
  columnTypes: ColumnType[];
  rowIds: string[];
  rows: string[][];
};

function sheet(
  id: string,
  name: string,
  columns: string[],
  columnTypes: ColumnType[],
  rows: string[][],
): SeedSheet {
  return {
    id,
    name,
    columns,
    columnTypes,
    rowIds: rows.map((_, index) => `${id}-row-${index + 1}`),
    rows,
  };
}

const sheets = [
  sheet(
    "dim-material",
    "DIM_MATERIAL",
    [
      "ID",
      "MATERIAL_NO",
      "MATERIAL_NAME",
      "CAS_NO",
      "MATERIAL_TYPE",
      "CREATED_AT",
      "UPDATED_AT",
    ],
    ["number", "text", "text", "text", "text", "date", "date"],
    [
      [
        "1",
        "M1001",
        "수성 아크릴 수지",
        "9003-01-4",
        "원재료",
        "2026-08-01",
        "2026-08-11",
      ],
      ["2", "M1002", "에탄올", "64-17-5", "용제", "2026-08-01", "2026-08-11"],
      [
        "3",
        "M1003",
        "이산화티타늄",
        "13463-67-7",
        "안료",
        "2026-08-01",
        "2026-08-11",
      ],
    ],
  ),
  sheet(
    "dim-vendor",
    "DIM_VENDOR",
    [
      "ID",
      "VENDOR_CODE",
      "VENDOR_NAME",
      "VENDOR_ADDRESS",
      "CREATED_AT",
      "UPDATED_AT",
    ],
    ["number", "text", "text", "text", "date", "date"],
    [
      [
        "101",
        "V001",
        "한국화학",
        "울산광역시 남구",
        "2026-08-01",
        "2026-08-11",
      ],
      ["102", "V002", "대한소재", "경기도 화성시", "2026-08-01", "2026-08-11"],
      [
        "103",
        "V003",
        "세진산업",
        "충청남도 천안시",
        "2026-08-01",
        "2026-08-11",
      ],
    ],
  ),
  sheet(
    "fact-msds-comp",
    "FACT_MSDS_COMP",
    [
      "ID",
      "MATERIAL_ID",
      "PARENT_COMP_ID",
      "COMP_NAME",
      "CAS_NO",
      "CONTENT_MIN",
      "CONTENT_MAX",
      "CONTENT_REP",
      "REFINED_AT",
      "VENDOR_ID",
      "SNAPSHOT_VERSION",
    ],
    [
      "number",
      "number",
      "number",
      "text",
      "text",
      "number",
      "number",
      "number",
      "date",
      "number",
      "number",
    ],
    [
      [
        "1001",
        "1",
        "",
        "아크릴 중합체",
        "9003-01-4",
        "0.45",
        "0.55",
        "0.50",
        "2026-08-11",
        "101",
        "1",
      ],
      [
        "1002",
        "2",
        "",
        "에탄올",
        "64-17-5",
        "0.10",
        "0.15",
        "0.12",
        "2026-08-11",
        "102",
        "1",
      ],
      [
        "1003",
        "1",
        "1001",
        "잔류 모노머",
        "79-10-7",
        "0.001",
        "0.005",
        "0.003",
        "2026-08-11",
        "101",
        "1",
      ],
    ],
  ),
  sheet(
    "stg-seh-msds",
    "STG_SEH_MSDS_SUBSTANCE",
    [
      "INGEST_ID",
      "MATERIAL_CODE",
      "SUPPLY_VENDOR_CODE",
      "EVAL_PLANT_CODE",
      "SUBSTANCE_SEQ",
      "MATERIAL_NAME",
      "EVAL_PLANT_NAME",
      "REQUEST_DATE",
      "APPR_DATE",
      "SUPPLY_VENDOR_NAME",
      "SUBSTANCE_NAME_KO",
      "SUBSTANCE_NAME_EN",
      "CAS_NO",
      "MIN_QUANTITY",
      "MAX_QUANTITY",
      "INGESTED_AT",
      "STATUS",
      "BATCH_ID",
      "SysStart",
      "SysEnd",
    ],
    [
      "number",
      "text",
      "text",
      "text",
      "number",
      "text",
      "text",
      "date",
      "date",
      "text",
      "text",
      "text",
      "text",
      "number",
      "number",
      "date",
      "text",
      "number",
      "date",
      "date",
    ],
    [
      [
        "2001",
        "M1001",
        "V001",
        "P100",
        "1",
        "수성 아크릴 수지",
        "울산공장",
        "2026-08-01",
        "2026-08-05",
        "한국화학",
        "아크릴 중합체",
        "Acrylic polymer",
        "9003-01-4",
        "45",
        "55",
        "2026-08-11",
        "C",
        "7001",
        "2026-08-11",
        "9999-12-31",
      ],
      [
        "2002",
        "M1002",
        "V002",
        "P100",
        "1",
        "에탄올",
        "울산공장",
        "2026-08-02",
        "2026-08-06",
        "대한소재",
        "에탄올",
        "Ethanol",
        "64-17-5",
        "95",
        "99.9",
        "2026-08-11",
        "C",
        "7001",
        "2026-08-11",
        "9999-12-31",
      ],
      [
        "2003",
        "M1003",
        "V003",
        "P200",
        "1",
        "이산화티타늄",
        "화성공장",
        "2026-08-03",
        "",
        "세진산업",
        "이산화티타늄",
        "Titanium dioxide",
        "13463-67-7",
        "98",
        "100",
        "2026-08-11",
        "N",
        "7002",
        "2026-08-11",
        "9999-12-31",
      ],
    ],
  ),
  sheet(
    "stg-seh-msds-hist",
    "STG_SEH_MSDS_SUBSTANCE_HIST",
    [
      "INGEST_ID",
      "MATERIAL_CODE",
      "SUPPLY_VENDOR_CODE",
      "EVAL_PLANT_CODE",
      "SUBSTANCE_SEQ",
      "MATERIAL_NAME",
      "EVAL_PLANT_NAME",
      "REQUEST_DATE",
      "APPR_DATE",
      "SUPPLY_VENDOR_NAME",
      "SUBSTANCE_NAME_KO",
      "SUBSTANCE_NAME_EN",
      "CAS_NO",
      "MIN_QUANTITY",
      "MAX_QUANTITY",
      "INGESTED_AT",
      "STATUS",
      "BATCH_ID",
      "SysStart",
      "SysEnd",
    ],
    [
      "number",
      "text",
      "text",
      "text",
      "number",
      "text",
      "text",
      "date",
      "date",
      "text",
      "text",
      "text",
      "text",
      "number",
      "number",
      "date",
      "text",
      "number",
      "date",
      "date",
    ],
    [
      [
        "2001",
        "M1001",
        "V001",
        "P100",
        "1",
        "수성 아크릴 수지",
        "울산공장",
        "2026-07-15",
        "",
        "한국화학",
        "아크릴 수지",
        "Acrylic resin",
        "9003-01-4",
        "40",
        "55",
        "2026-07-16",
        "N",
        "6901",
        "2026-07-16",
        "2026-08-11",
      ],
      [
        "2002",
        "M1002",
        "V002",
        "P100",
        "1",
        "에탄올",
        "울산공장",
        "2026-07-16",
        "",
        "대한소재",
        "에탄올",
        "Ethanol",
        "64-17-5",
        "90",
        "99.9",
        "2026-07-17",
        "N",
        "6901",
        "2026-07-17",
        "2026-08-11",
      ],
    ],
  ),
  sheet(
    "stg-sap-zapc",
    "STG_SAP_ZAPC2R1050",
    [
      "INGEST_ID",
      "BATCH_NO",
      "REQUEST_SPMON",
      "ROW_NO",
      "INGEST_DT",
      "STATUS",
      "WERKS",
      "MATNR",
      "MAKTX",
      "ELEMT",
      "TXELE",
      "OWERKS",
      "OMATNR",
      "OMAKTX",
      "LSTAR",
      "KOSTL",
      "KTEXT",
      "KSTAR",
      "LTEXT",
      "MENGE",
      "ZTOT",
      "BDATJ",
      "POPER",
      "PRODH",
      "SysStart",
      "SysEnd",
    ],
    [
      "number",
      "number",
      "text",
      "number",
      "date",
      "text",
      "text",
      "text",
      "text",
      "text",
      "text",
      "text",
      "text",
      "text",
      "text",
      "text",
      "text",
      "text",
      "text",
      "number",
      "number",
      "text",
      "text",
      "text",
      "date",
      "date",
    ],
    [
      [
        "3001",
        "8001",
        "202608",
        "1",
        "2026-08-11",
        "C",
        "P100",
        "M1001",
        "수성 아크릴 수지",
        "MAT",
        "직접재료비",
        "P100",
        "M1002",
        "에탄올",
        "MIX01",
        "CC100",
        "혼합공정",
        "500100",
        "원재료비",
        "1250",
        "4875000",
        "2026",
        "08",
        "CHEM01",
        "2026-08-11",
        "9999-12-31",
      ],
      [
        "3002",
        "8001",
        "202608",
        "2",
        "2026-08-11",
        "C",
        "P200",
        "M1003",
        "이산화티타늄",
        "MAT",
        "직접재료비",
        "P200",
        "M1001",
        "수성 아크릴 수지",
        "COAT01",
        "CC200",
        "코팅공정",
        "500100",
        "원재료비",
        "820",
        "3280000",
        "2026",
        "08",
        "CHEM02",
        "2026-08-11",
        "9999-12-31",
      ],
      [
        "3003",
        "8002",
        "202608",
        "3",
        "2026-08-11",
        "N",
        "P100",
        "M1002",
        "에탄올",
        "ACT",
        "가공비",
        "P100",
        "",
        "",
        "DRY01",
        "CC110",
        "건조공정",
        "600200",
        "전력비",
        "410",
        "984000",
        "2026",
        "08",
        "CHEM01",
        "2026-08-11",
        "9999-12-31",
      ],
    ],
  ),
  sheet(
    "stg-sap-zapc-hist",
    "STG_SAP_ZAPC2R1050_HIST",
    [
      "INGEST_ID",
      "BATCH_NO",
      "REQUEST_SPMON",
      "ROW_NO",
      "INGEST_DT",
      "STATUS",
      "WERKS",
      "MATNR",
      "MAKTX",
      "ELEMT",
      "TXELE",
      "OWERKS",
      "OMATNR",
      "OMAKTX",
      "LSTAR",
      "KOSTL",
      "KTEXT",
      "KSTAR",
      "LTEXT",
      "MENGE",
      "ZTOT",
      "BDATJ",
      "POPER",
      "PRODH",
      "SysStart",
      "SysEnd",
    ],
    [
      "number",
      "number",
      "text",
      "number",
      "date",
      "text",
      "text",
      "text",
      "text",
      "text",
      "text",
      "text",
      "text",
      "text",
      "text",
      "text",
      "text",
      "text",
      "text",
      "number",
      "number",
      "text",
      "text",
      "text",
      "date",
      "date",
    ],
    [
      [
        "3001",
        "7901",
        "202607",
        "1",
        "2026-07-31",
        "C",
        "P100",
        "M1001",
        "수성 아크릴 수지",
        "MAT",
        "직접재료비",
        "P100",
        "M1002",
        "에탄올",
        "MIX01",
        "CC100",
        "혼합공정",
        "500100",
        "원재료비",
        "1200",
        "4560000",
        "2026",
        "07",
        "CHEM01",
        "2026-07-31",
        "2026-08-11",
      ],
      [
        "3002",
        "7901",
        "202607",
        "2",
        "2026-07-31",
        "C",
        "P200",
        "M1003",
        "이산화티타늄",
        "MAT",
        "직접재료비",
        "P200",
        "M1001",
        "수성 아크릴 수지",
        "COAT01",
        "CC200",
        "코팅공정",
        "500100",
        "원재료비",
        "800",
        "3120000",
        "2026",
        "07",
        "CHEM02",
        "2026-07-31",
        "2026-08-11",
      ],
    ],
  ),
  sheet(
    "stg-sap-zcor0080",
    "STG_SAP_ZCOR0080",
    [
      "INGEST_ID",
      "BATCH_NO",
      "REQUEST_SPMON",
      "ROW_NO",
      "INGEST_DT",
      "STATUS",
      "WERKS",
      "WAERS",
      "GJAHR",
      "PERIO",
      "MATNR",
      "MAKTX",
      "VERID",
      "TEXT1",
      "PRDHA_3",
      "KSTAR",
      "IDNRK",
      "MAKTX2",
      "QTY",
      "ZEAAMOUNT",
    ],
    [
      "number",
      "number",
      "text",
      "number",
      "date",
      "text",
      "text",
      "text",
      "text",
      "text",
      "text",
      "text",
      "text",
      "text",
      "text",
      "text",
      "text",
      "text",
      "number",
      "number",
    ],
    [
      [
        "4001",
        "8101",
        "202608",
        "1",
        "2026-08-11",
        "C",
        "P100",
        "KRW",
        "2026",
        "08",
        "M1001",
        "수성 아크릴 수지",
        "V001",
        "표준생산",
        "CHEM01",
        "500100",
        "M1002",
        "에탄올",
        "1250",
        "4875000",
      ],
      [
        "4002",
        "8101",
        "202608",
        "2",
        "2026-08-11",
        "C",
        "P200",
        "KRW",
        "2026",
        "08",
        "M1003",
        "이산화티타늄",
        "V001",
        "표준생산",
        "CHEM02",
        "500100",
        "M1001",
        "수성 아크릴 수지",
        "820",
        "3280000",
      ],
      [
        "4003",
        "8102",
        "202608",
        "3",
        "2026-08-11",
        "N",
        "P100",
        "KRW",
        "2026",
        "08",
        "M1002",
        "에탄올",
        "V002",
        "시험생산",
        "CHEM01",
        "500100",
        "M1003",
        "이산화티타늄",
        "300",
        "1200000",
      ],
    ],
  ),
  sheet(
    "stg-sap-zcot0110",
    "STG_SAP_ZCOT0110",
    [
      "INGEST_ID",
      "BATCH_NO",
      "REQUEST_SPMON",
      "ROW_NO",
      "INGEST_DT",
      "STATUS",
      "KOKRS",
      "GJAHR",
      "PERIO",
      "OBJNR",
      "STAGR",
      "LTEXT",
      "SMEXXX",
      "MEINH",
      "WTGXXX",
    ],
    [
      "number",
      "number",
      "text",
      "number",
      "date",
      "text",
      "text",
      "text",
      "text",
      "text",
      "text",
      "text",
      "number",
      "text",
      "number",
    ],
    [
      [
        "5001",
        "8201",
        "202608",
        "1",
        "2026-08-11",
        "C",
        "1000",
        "2026",
        "08",
        "KSCC100",
        "ENERGY",
        "혼합공정 전력사용량",
        "15200",
        "KWH",
        "2280000",
      ],
      [
        "5002",
        "8201",
        "202608",
        "2",
        "2026-08-11",
        "C",
        "1000",
        "2026",
        "08",
        "KSCC200",
        "STEAM",
        "코팅공정 스팀사용량",
        "8400",
        "KG",
        "1260000",
      ],
      [
        "5003",
        "8202",
        "202608",
        "3",
        "2026-08-11",
        "N",
        "1000",
        "2026",
        "08",
        "KSCC110",
        "WATER",
        "건조공정 용수사용량",
        "620",
        "TON",
        "558000",
      ],
    ],
  ),
  sheet(
    "stg-sap-ke30",
    "STG_SAP_KE30",
    [
      "INGEST_ID",
      "BATCH_NO",
      "REQUEST_SPMON",
      "ROW_NO",
      "INGEST_DT",
      "STATUS",
      "PAPH3",
      "SALES",
      "SALES_UNIT",
      "GJAHR",
      "POPER",
      "ARTNR",
    ],
    [
      "number",
      "number",
      "text",
      "number",
      "date",
      "text",
      "text",
      "number",
      "text",
      "text",
      "text",
      "text",
    ],
    [
      [
        "6001",
        "8301",
        "202608",
        "1",
        "2026-08-11",
        "C",
        "CHEM01",
        "125000000",
        "KRW",
        "2026",
        "08",
        "M1001",
      ],
      [
        "6002",
        "8301",
        "202608",
        "2",
        "2026-08-11",
        "C",
        "CHEM02",
        "87000000",
        "KRW",
        "2026",
        "08",
        "M1003",
      ],
      [
        "6003",
        "8302",
        "202608",
        "3",
        "2026-08-11",
        "N",
        "CHEM01",
        "34000000",
        "KRW",
        "2026",
        "08",
        "M1002",
      ],
    ],
  ),
] satisfies SeedSheet[];

function relation(
  id: string,
  sourceSheetId: string,
  sourceColumn: string,
  targetSheetId: string,
  targetColumn: string,
  relationType: "1:1" | "1:N" | "N:1" | "N:N",
) {
  const source = sheets.find((item) => item.id === sourceSheetId)!;
  const target = sheets.find((item) => item.id === targetSheetId)!;
  const sourceIndex = source.columns.indexOf(sourceColumn);
  const targetIndex = target.columns.indexOf(targetColumn);
  const links = source.rows.flatMap((sourceRow, sourceRowIndex) =>
    target.rows.flatMap((targetRow, targetRowIndex) =>
      sourceRow[sourceIndex] &&
      sourceRow[sourceIndex] === targetRow[targetIndex] &&
      (sourceSheetId !== targetSheetId || sourceRowIndex !== targetRowIndex)
        ? [
            {
              sourceRowId: source.rowIds[sourceRowIndex],
              targetRowId: target.rowIds[targetRowIndex],
            },
          ]
        : [],
    ),
  );
  return {
    id,
    sourceSheetId,
    sourceColumn,
    targetSheetId,
    targetColumn,
    relationType,
    updateOption: "none",
    links,
  };
}

const sheetRelations = [
  relation(
    "fk-msds-comp-material",
    "fact-msds-comp",
    "MATERIAL_ID",
    "dim-material",
    "ID",
    "N:1",
  ),
  relation(
    "fk-msds-comp-parent",
    "fact-msds-comp",
    "PARENT_COMP_ID",
    "fact-msds-comp",
    "ID",
    "N:1",
  ),
  relation(
    "ref-msds-comp-vendor",
    "fact-msds-comp",
    "VENDOR_ID",
    "dim-vendor",
    "ID",
    "N:1",
  ),
  relation(
    "ref-seh-msds-material",
    "stg-seh-msds",
    "MATERIAL_CODE",
    "dim-material",
    "MATERIAL_NO",
    "N:1",
  ),
  relation(
    "ref-seh-msds-vendor",
    "stg-seh-msds",
    "SUPPLY_VENDOR_CODE",
    "dim-vendor",
    "VENDOR_CODE",
    "N:1",
  ),
  relation(
    "ref-seh-msds-hist-material",
    "stg-seh-msds-hist",
    "MATERIAL_CODE",
    "dim-material",
    "MATERIAL_NO",
    "N:1",
  ),
  relation(
    "ref-seh-msds-hist-vendor",
    "stg-seh-msds-hist",
    "SUPPLY_VENDOR_CODE",
    "dim-vendor",
    "VENDOR_CODE",
    "N:1",
  ),
  relation(
    "temporal-seh-msds",
    "stg-seh-msds",
    "INGEST_ID",
    "stg-seh-msds-hist",
    "INGEST_ID",
    "1:N",
  ),
  relation(
    "ref-zapc-material",
    "stg-sap-zapc",
    "MATNR",
    "dim-material",
    "MATERIAL_NO",
    "N:1",
  ),
  relation(
    "ref-zapc-origin-material",
    "stg-sap-zapc",
    "OMATNR",
    "dim-material",
    "MATERIAL_NO",
    "N:1",
  ),
  relation(
    "temporal-zapc",
    "stg-sap-zapc",
    "INGEST_ID",
    "stg-sap-zapc-hist",
    "INGEST_ID",
    "1:N",
  ),
  relation(
    "ref-zcor0080-material",
    "stg-sap-zcor0080",
    "MATNR",
    "dim-material",
    "MATERIAL_NO",
    "N:1",
  ),
  relation(
    "ref-zcor0080-component",
    "stg-sap-zcor0080",
    "IDNRK",
    "dim-material",
    "MATERIAL_NO",
    "N:1",
  ),
  relation(
    "ref-ke30-material",
    "stg-sap-ke30",
    "ARTNR",
    "dim-material",
    "MATERIAL_NO",
    "N:1",
  ),
];

async function main() {
  const current = await prisma.project.findFirst({
    where: { name: "LCA 데이터 정제", deletedAt: null },
    orderBy: { updatedAt: "desc" },
  });
  const projectId = current?.id ?? crypto.randomUUID();
  const currentDocument =
    current?.document &&
    typeof current.document === "object" &&
    !Array.isArray(current.document)
      ? (current.document as Record<string, Prisma.JsonValue>)
      : {};
  const firstSheet = sheets[0];
  const document: Prisma.InputJsonObject = {
    ...currentDocument,
    schemaVersion: 7,
    sheets,
    sheetRelations,
    calculatedFields: [],
    displayBindings: {},
    dataBinding: {
      primarySheet: firstSheet.id,
      joinedSheet: sheets[1].id,
      linkSourceId: firstSheet.id,
      connectionPath: [firstSheet.id],
      selectedCandidateId: "",
      relationType: "1:1",
    },
  };

  await prisma.project.upsert({
    where: { id: projectId },
    update: {
      name: "LCA 데이터 정제",
      document,
      version: { increment: 1 },
    },
    create: {
      id: projectId,
      name: "LCA 데이터 정제",
      document,
    },
  });
}

main().finally(async () => {
  await prisma.$disconnect();
});
